### ISSUE TITLE
[Waiting for Zenodo response]: implement Zenodo publication fetch_all

### ISSUE THREAD

**Issue by josvandervelde** [aiondemand/AIOD-rest-api#23]
For the `fetch_all` we want to use something like https://zenodo.org/api/records?size=10? 
But... It gives an error when trying to access more than the first 10000 items. Even with
https://zenodo.org/api/records/?size=1&page=10001

Íñigo has asked Zenodo for support.

**Comment by arejula27** [comment]
They answered and told me that we might do the pagination based on date instead pages. The query doc doesnt explain how to do it so i will keep in touch with them

**Comment by josvandervelde** [comment]
Pagination based on date is implemented. I assume that this issue can be closed.
