### ISSUE TITLE
Delete branch on merge?

### ISSUE THREAD

**Issue by PGijsbers** [aiondemand/AIOD-rest-api#260]
There are [a lot of branches](https://github.com/aiondemand/AIOD-rest-api/branches) in this project, and most of them have already been merged. In order to keep a better overview, I suggest we delete all branches which have been merged into `develop`, and to turn on the Github setting to delete branches automatically on a merge.

**Comment by jsmatias** [comment]
Indeed, there are too many branches. 
I never deleted a branch that was fully developed and merged, but I assume that the history of the commits, PRs, etc. doesn't change. In that case we can probably do as you suggested.

**Comment by PGijsbers** [comment]
I do not have the permission to change these settings.
