### ISSUE TITLE
Handle User Privacy issues | API should not reveal personal information

### ISSUE THREAD

**Issue by AlexJoom** [aiondemand/AIOD-rest-api#293]
The contact email addresses, and the Person's first name and last name  should be hidden on get requests, unless you are the owner who posted the AIoD entity

**Comment by AlexJoom** [comment]
Notice that in events, we have a "Performer" property, that maps to the speakers of the event (Person object)

In this case we should display their First name and Last Name

At the moment, the get request for events returns only the Ids of the people, so it's not possible to display them.


Ideally we should now if Persons have given consent their information to be publicly available.

A short solution for the events would be to return the whole person object instead of the ids

**Comment by jsmatias** [comment]
I linked this issue to PR #298 to limit access to sensitive information. 

Regrading the second comment, quoted below:
> Notice that in events, we have a "Performer" property, that maps to the speakers of the event (Person object)
> 
> In this case we should display their First name and Last Name
> 
> At the moment, the get request for events returns only the Ids of the people, so it's not possible to display them.
> 
> Ideally we should know if Persons have given consent their information to be publicly available.
> 
> A short solution for the events would be to return the whole person object instead of the ids

This can be further discussed and addressed in a separate PR, if needed.
