### ISSUE TITLE
Detailed platform counts error (in production)

### ISSUE THREAD

**Issue by PGijsbers** [aiondemand/AIOD-rest-api#319]
The query `https://api.aiod.eu/counts/platforms/v1?detailed=true` fails with `{
  "detail": "Unexpected exception while processing your request. Please contact the maintainers: type object 'Platform' has no attribute 'platform'"
}`

I have not tested the reproducibility of this bug in other environments.

**Comment by andrejridzik** [comment]
This is a duplicate of already resolved issue #365
