### ISSUE TITLE
Platform counts does not actually allow `detailed=True`

### ISSUE THREAD

**Issue by PGijsbers** [aiondemand/AIOD-rest-api#365]
https://api.aiod.eu/docs#/platforms/Count_of_platforms_counts_platforms_v1_get

This makes sense, as the number of platforms per platform... doesn't really work. Yet because of the shared logic, the `detailed` parameter is still part of the interface. It should be removed. Potentially, to indicate the difference, an endpoint with a distinct name could be used instead.

**Comment by andrejridzik** [comment]
Fixed by separating the Platform endpoints and removing the `detailed` parameter.
